/* SPDX-License-Identifier: BSD-3-Clause */
/**********************************************************************
 * Copyright (C) 2012-2020 Cadence Design Systems, Inc.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************
 */

#ifndef INCLUDE_CDN_STDTYPES_H___
#define INCLUDE_CDN_STDTYPES_H___
#ifdef __KERNEL__
#include <linux/types.h>
#else
#include "cdn_stdint.h"
#include <stddef.h>
#include <stdbool.h>
#ifdef __cplusplus
extern "C" {
#endif

#endif /* __KERNEL__ */
#ifdef __cplusplus
}
#endif

#endif  /* INCLUDE_CDN_STDTYPES_H__ */
