# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2019 Texas Instruments Incorporated - http://www.ti.com/
#

obj-$(CONFIG_K3_AM64_DDRSS) += k3-am64-ddrss.o
obj-$(CONFIG_K3_AM64_DDRSS) += lpddr4_obj_if.o
obj-$(CONFIG_K3_AM64_DDRSS) += lpddr4.o
