# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-$(CONFIG_TARGET_AM335X_LIERDA)		:= mux.o
endif

obj-$(CONFIG_TARGET_AM335X_LIERDA)		+= board.o
